RA-03-create-navigation-buttons
toto-neutrino1/RecipeApp pull request #1
Opened 2023-12-07 12:24 UTC by toto-neutrino1

2023-12-07 19:26 UTC, ievetrovdev commented
Нейминги следует делать все в едином стиле (который принят в сообществе)

RA-03 create navigation buttons (для названия ПР и сообщения коммита)
RA-03-create-navigation-buttons (для названия ветки)

2023-12-07 20:05 UTC, ievetrovdev requested changes

2023-12-07 20:05 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +    android:background="@color/alice_blue">
- Про ресурсы цветов: следует выбрать некий определенный стиль названия айдишников. Можно делать название в стиле назначения или использовать названия цветов. Но самое основное – рекомендую ко всем цветам добавлять color в конце. Чтобы если что можно было легко искать применение этого цвета по всему проекту.
- Самые часто применяемые цвета можно назвать максимально понятно по назначению, например, main_background_color

2023-12-07 20:05 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            app:icon="@drawable/ic_heart"
а откуда ты выгружал эту иконку? в макете у нее другое название и в приложении она как будто другой формы

2023-12-07 20:05 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:text="@string/button_categories"/>
По строковым ресурсам (как и с цветами) следует обозначать, что это относится к строке. Пока название ресурса говорит о том, что это айди кнопки условно. Кроме того строка "Категории" будет использоваться и как заголовок экрана. Поэтому предлагаю назвать, например, так title_categories.

2023-12-07 20:05 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="horizontal_margin_main">16dp</dimen>
тут ок. можно сделать основной main и half как второй по популярности отступ

2023-12-07 20:05 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="btn_corner_radius">8dp</dimen>
это значение относится не только к кнопкам. поэтому значение btn лучше не использовать (а конкретизировать название уже в стилях).

2023-12-07 20:05 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="btn_text_size">14sp</dimen>
Давай в файле добавим визуальное разделение (можно с информационным комментарием) на размеры отступов и размеры шрифтов

2023-12-07 20:05 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/montserrat_alternates_regular</item>
посмотри внимательнее какая толщина шрифта кнопок по макету

2023-12-07 20:05 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="@dimen/btn_bottom_margin"
очень большой отступ. в макете за границу экрана считаем стандартный навбар

2023-12-08 12:24 UTC, toto-neutrino1 commented on app/src/main/res/layout/activity_main.xml
> +            app:icon="@drawable/ic_heart"
Из фигмы (https://www.figma.com/file/89K5JomHGyIkUFUaBKRBXi/RecipesApp?type=design&node-id=0-3&mode=design&t=WVrt9lSiAT2PXlt9-0) - в названии только "ic" в начале добавил.

А насчёт размеров - на фигме они 21 x 18, у меня - 22 x 18, т.к. при экспорте иконки в Drawable Android Studio почему-то не дала задать размер 21 x 18 (при корректировке одного измерения автоматически менялось другое).

Поправил в в файле ic_heart.xml width (viewportWidth менять не стал, т.к. края обрезались).

2023-12-08 12:55 UTC, toto-neutrino1 commented on app/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/montserrat_alternates_regular</item>
Я же правильно понял, что толщина в Figma указывается параметром "weight"?

2023-12-08 12:56 UTC, toto-neutrino1 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="@dimen/btn_bottom_margin"
Вроде всё исправил

2023-12-08 15:20 UTC, ievetrov commented on app/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/montserrat_alternates_regular</item>
да. общепринятый для многих сфер (типа веба) параметр

2023-12-08 15:25 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            app:icon="@drawable/ic_heart"
понял, выгружай фрейм, а не иконку. тогда экспорт будет без ошибок

<img width="467" alt="Снимок экрана 2023-12-08 в 19 24 58" src="https://github.com/toto-neutrino1/RecipeApp/assets/34489023/2ec80dcb-ed73-4392-9f8f-dc78af464d87">

2023-12-08 15:25 UTC, ievetrov requested changes
вопросик с иконкой решим и все

2023-12-08 16:24 UTC, toto-neutrino1 commented on app/src/main/res/layout/activity_main.xml
> +            app:icon="@drawable/ic_heart"
Понял, спасибо!

2023-12-09 08:25 UTC, ievetrov approved these changes

2023-12-09 08:25 UTC, ievetrov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="vertical_padding">10dp</dimen>
направление не храним. пусть будет хоть диагональным. но вот како-то единый стиль можно подобрать и их очень много. например, https://medium.com/@june.pravin/dimensions-by-conventions-92b422e2216e

2023-12-10 14:36 UTC, toto-neutrino1 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="vertical_padding">10dp</dimen>
Классная статья, спасибо!

2023-12-10 14:36 UTC, merged