RA 13 implement recipe screen without ingredients count
toto-neutrino1/RecipeApp pull request #11
Opened 2024-01-24 20:20 UTC by toto-neutrino1

2024-01-25 13:54 UTC, ievetrov requested changes
Также немного смущает разнообразие стилей написания item_list_recipes и более часто используемый item_category. Предлагаю первый привести в соответствие остальным оейаутам айтемов

2024-01-25 13:54 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/screens/recipe/RecipeFragment.kt
> +                        ),
довольно размашесто по вертикали получилось, давай частично сократим количество строк

2024-01-25 13:54 UTC, ievetrov commented on app/src/main/res/values/strings.xml
> +    <string name="cont_descr_iv_recipes_burgers" translatable="false">Изображение рецепты бургеры</string>
cont_descr_iv_recipes_burgers выглядит как захардкоженное значение. В проекте используется для списка рецептов. надо или задавать динамически для каждой переданной категории, или задать более общее описание и название ресурса

2024-01-25 14:01 UTC, ievetrov requested changes
Также обрати внимание на макет
- чуть надо поработать с отступами ингредиентов и метода приготовления. 
- также положение в этих айтемах не мдеально (по вертикали)
- дивайдер не заполняет всю ширину подложки
- подложка списков имеет скругленные края

2024-01-26 18:23 UTC, toto-neutrino1 commented
Невнимательно прочитал про то, как работать с ItemDecoration, поэтому долго тупил, как разделители сделать не на всю длину подложки, думал, что это можно сделать только с помощью метода **getItemOffsets()**, а оказалось, что он совсем не нужен, и нужно лишь переопределить метод **onDraw()**

2024-01-27 11:16 UTC, ievetrov requested changes
Также надо учесть длинные названия. Текст должен переноситься с аналогичным отступом справа

<img width="333" alt="Снимок экрана 2024-01-27 в 14 15 15" src="https://github.com/toto-neutrino1/RecipeApp/assets/34489023/f8d1f1bc-f053-449f-8187-da381758b69c">

2024-01-27 11:16 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/screens/recipeList/RecipesListAdapter.kt
>              with(viewHolder.ivListRecipesImage) {
ivListRecipesImage имеет высоту изображения не по макету, этот же лейаут лучше переименовать например в item_recipe. айтем обычно называется в единственном числе

2024-01-27 11:16 UTC, ievetrov commented on app/src/main/res/layout/item_ingredient.xml
> +        android:text="Подсолнечное масло"
Эти значения сюда приходят из адаптера, а когда данные будут грузиться из сети с задержкой – чревато мельканием текста. Лучше вынести в tools, чтобы значения были видны только на превью в студии.

2024-01-27 11:16 UTC, ievetrov commented on app/src/main/res/layout/item_ingredient.xml
> +        android:text="Подсолнечное масло"
Стиль этого текста отличается от макета

2024-01-27 11:16 UTC, ievetrov commented on app/src/main/res/layout/item_ingredient.xml
> +        android:textAllCaps="true"
тоже можно вынести в стиль

2024-01-27 13:58 UTC, toto-neutrino1 commented on app/src/main/res/layout/item_ingredient.xml
> +        android:text="Подсолнечное масло"
> Стиль этого текста отличается от макета

Не нашёл отличий: шрифт Montserrat_Regular (weight = 400), размер - 14, текст - большими буквами.
Можешь пожалуйста подсказать, что я пропустил?

2024-01-27 14:29 UTC, toto-neutrino1 commented on app/src/main/res/layout/item_ingredient.xml
> +        android:text="Подсолнечное масло"
Вопрос про **item_ingredient.xml**: во втором TextView (с id = tvIngredientQuantityText) я решил убрать ширину - нормально ли так делать?
Убрал ширину по следующим причинам:
1) если **layout_width** оставить равным **wrap_content**, то тексты слева и справа могут наехать друг на друга, если правый текст будет длинным (привязка правого TV к концу левого TV решала бы проблему, но тогда текст в правом TV не был бы расположен с правой стороны экрана)
2) **layout_width = "match_parent"** - тоже плохо, т.к. тексты будут наезжать друг на друга.
3) Фиксированная ширина правого TV - возможный вариант решения, но на разных экранах будет смотреться по-разному.
4) Можно заменить ConstraintLayout на LinearLayout, тогда этой проблемы совсем не будет; но единообразия стилей для макетов **item_...** тогда не будет.

Как советуешь поступить в данном случае?

2024-01-27 14:55 UTC, toto-neutrino1 commented on app/src/main/res/layout/item_ingredient.xml
> +        android:text="Подсолнечное масло"
Ещё в файле **item_ingredient.xml** меня смущает фиксированная ширина у TextViews (т.к. размеры у разных устройств разные) - по идее, лучше указывать размеры такие, чтобы в итоге TextViews вместе занимали всю ширину родительского контейнера. Или всё ок и оставляем с фиксированными ширинами?

2024-01-27 22:13 UTC, toto-neutrino1 commented
> [app/src/main/res/layout/item_ingredient.xml](https://github.com/toto-neutrino1/RecipeApp/pull/11/files/a1864659e6143423fa63b6dcca7c66f9e2103250#diff-bfe1ecbfe805380d14aa938d3f20ddfcb39ee9110eff2ffb4de1357507def636)
> Стиль этого текста отличается от макета

Под этим комментарием написал 2 вопроса

2024-01-27 22:38 UTC, ievetrov approved these changes
Все отлично, по шрифтам ингредиента я кажется дезинформировал, сорри.

2024-01-27 22:40 UTC, merged