RA-14 add seekBar for ingredients calculating
toto-neutrino1/RecipeApp pull request #12
Opened 2024-02-05 21:45 UTC by toto-neutrino1

2024-02-05 22:03 UTC, toto-neutrino1 commented
Вопрос про методы для **OnSeekBarChangeListener** - есть ли какие-то советы/примеры, в каких случаях нужно реализовывать какие из них?

Каких-то адекватных примеров нагуглить не удалось, каждый прописывает как хочет, реализовывая **onProgressChanged()** и/или **onStopTrackingTouch()** (зачастую прописывая один и тот же код или в одном, или в другом методе); но реализации **onStartTrackingTouch()** кроме как для логирования не встречал нигде

2024-02-06 11:53 UTC, ievetrov commented
> Вопрос про методы для **OnSeekBarChangeListener** - есть ли какие-то советы/примеры, в каких случаях нужно реализовывать какие из них?
> 
> Каких-то адекватных примеров нагуглить не удалось, каждый прописывает как хочет, реализовывая **onProgressChanged()** и/или **onStopTrackingTouch()** (зачастую прописывая один и тот же код или в одном, или в другом методе); но реализации **onStartTrackingTouch()** кроме как для логирования не встречал нигде

Любые действия исходят из мотива. Интерфейс требует переопределения всех трех методов, в джавадоке есть описание каждого из них для тонкой настройке вьюх, с которым взаимодействует пользователь. Сикбар может использоваться для разных целей, например, фильтрация, поиск, сортировка итд. В зависимости от бизнес логики можем вызывать методы в разный момент взаимодействия с ползунком

<img width="671" alt="Снимок экрана 2024-02-06 в 14 47 37" src="https://github.com/toto-neutrino1/RecipeApp/assets/34489023/d5ba32e1-dc82-48ef-b304-5f92fbd28f17">

2024-02-06 11:56 UTC, ievetrov requested changes
Хорошо, по адаптерам еще отписал в ЛС

2024-02-06 11:56 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/screens/recipe/RecipeFragment.kt
> +                        rvIngredients.adapter?.notifyDataSetChanged()
Предлагаю внутри updateIngredients обновлять датасет

2024-02-06 11:56 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/screens/recipe/IngredientsAdapter.kt
> +            if (componentQuantity.endsWith(".0")) {
Ок, немного не нравится жесткое сравнение со строкой. Попробуй что-то взять из альтернативной реализации

<img width="687" alt="Снимок экрана 2024-02-06 в 14 54 25" src="https://github.com/toto-neutrino1/RecipeApp/assets/34489023/fd529723-44cc-4061-a943-7933a3f7d3ba">

2024-02-06 14:32 UTC, toto-neutrino1 commented on app/src/main/java/com/example/recipeapp/screens/recipe/IngredientsAdapter.kt
> +            if (componentQuantity.endsWith(".0")) {
Чуть поправил. 
Но сравниваю всё равно строки, т.к. сравнение с помощью "==" чисел с плавающей точкой не рекомендуется (из-за невозможности точного представления дробной части в двоичной системе для практически всех десятичных чисел).

2024-02-06 17:20 UTC, toto-neutrino1 commented on app/src/main/java/com/example/recipeapp/screens/recipe/RecipeFragment.kt
> +                        rvIngredients.adapter?.notifyDataSetChanged()
Сделал. Для этого пришлось в класс **Recipe** добавить свойство **numOfPortions** - т.к. при выходе с экрана с конкретным рецептом и последующим возвратом на него нужно было помнить, в расчёте на сколько порций на данный момент для данного рецепта указано количество ингредиентов.

Пояснение: при выходе с экрана с конкретным рецептом, когда seekBar не в минимальном положении и последующим возвратом на этот же экран, минимальное количество порций становилось другим; например, если мы были на экране с рецептом "Чизбургер", с seekBar в положении 4, то при выходе с этого экрана и последующим возвратом на него, ползунок находился в положении 1, но минимальное количество порций становилось равным 4 (при перемещении ползунка количество порций становилось кратным 4:   4, 8, 16, 20).

2024-02-09 13:14 UTC, ievetrov approved these changes

2024-02-09 15:56 UTC, merged