RA-20 create view model for recipes and entity for state
toto-neutrino1/RecipeApp pull request #18
Opened 2024-02-21 17:57 UTC by toto-neutrino1

1. В целом, для класса **RecipeUiState** мне достаточно хранить только первые 2 переменные (**categoryId** и **recipeId**), т.к. данные для конкретного рецепта буду получать из объекта STUB.
2. Переменные **numOfPortions** и **isInFavorites** - на данном этапе они уже есть в классе **Recipe**, но логично их будет вынести сюда (пока из класса **Recipe** их не убрал, чтобы всё работало, сделаю это в следующих PR).

2024-02-22 12:15 UTC, ievetrov requested changes

2024-02-22 12:15 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    var categoryId: Int = 0,
айди категории у нас не будет динамически меняться, а также мы его не получаем из хранилища. здесь это значение выступает как переданный во фрагмент ключ, по которому будет осуществляться поиск определенного рецепта. далее мы будем передавать его в из фрагмента во вьюмодель в метод загрузки рецепта. в стейте он использоваться не будет

2024-02-22 12:15 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    var recipeId: Int = 0,
я бы предложил здесь использовать объект рецепта целиком, тк нам нужно будет отрисовывать и заголовок, и описание и все остальное.

2024-02-22 12:15 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    var isInFavorites: Boolean = false
логично, что это свойство должно быть в стейте. будем менять его напрямую из методов сохранения загрузки из SP. но не через свойство класса Recipe

2024-02-23 13:37 UTC, ievetrovdev approved these changes

2024-02-23 14:20 UTC, merged