RA-04 create first categories fragment
toto-neutrino1/RecipeApp pull request #2
Opened 2023-12-15 13:02 UTC by toto-neutrino1

2023-12-15 16:34 UTC, ievetrov requested changes

2023-12-15 16:34 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            val fragmentTransaction = fragmentManager.beginTransaction()
Работает, но предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). Именно для импорта этого метода и метода add() нужно было имплементировать библиотеку fragment-ktx.

2023-12-15 16:34 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:text="@string/tv_categories_list_fragment" />
смотри, строка может использоваться не только в текствью, а например в кнопке. а ресурс с названием tv_categories_list_fragment сужает логически его использование. предлагаю что-то более общное придумать

2023-12-15 19:17 UTC, toto-neutrino1 commented on app/src/main/res/layout/fragment_list_categories.xml
> +        android:text="@string/tv_categories_list_fragment" />
Да, ошибся, у меня текст "Категории" уже был ранее использован с более общим названием

2023-12-16 11:32 UTC, ievetrov approved these changes

2023-12-16 13:37 UTC, merged