RA-39 add cashing for category list
toto-neutrino1/RecipeApp pull request #36
Opened 2024-04-16 13:32 UTC by toto-neutrino1

2024-04-17 17:04 UTC, ievetrovdev requested changes

2024-04-17 17:04 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/RecipesDatabase.kt
> +        @Volatile
а зачем его используешь?

2024-04-17 17:04 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/RecipesDatabase.kt
> +            INSTANCE ?: synchronized(this) {
и тут зачем синхронизация? возникают какие-то проблемы?

2024-04-17 19:59 UTC, toto-neutrino1 commented on app/src/main/java/com/example/recipeapp/data/RecipesDatabase.kt
> +        @Volatile
1. Компаньон использую для того, чтобы экземпляр БД создавался один раз и переиспользовался.
2. Если же речь про волатильность - в комментарии ниже описал

2024-04-17 20:08 UTC, toto-neutrino1 commented on app/src/main/java/com/example/recipeapp/data/RecipesDatabase.kt
> +            INSTANCE ?: synchronized(this) {
Про синхронизацию и волатильность - проблем без них не возникало; мне просто в целом понравился этот подход, и решил его тут оставить (подход из codelab от google - https://developer.android.com/codelabs/android-room-with-a-view-kotlin#7).
То есть конкретно тут это необязательно, но я хочу оставить для себя как потенциально полезный пример

2024-04-19 06:06 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/RecipesDatabase.kt
> +            INSTANCE ?: synchronized(this) {
Понял ))
Хорошо, пусть будет. На самом деле этот момент разруливается позже на этапе внедрения Room

2024-04-19 06:16 UTC, ievetrovdev requested changes

2024-04-19 06:16 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/CategoriesDao.kt
> +    fun getCategories(): List<Category>?
тут оно не может быть nullable, просто пустой список, если нет записей

2024-04-19 06:16 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/RecipesRepository.kt
> +        return categories
тут можно сократить до:
```Kotlin
    suspend fun getCategoriesFromCash(): List<Category>? =
        withContext(Dispatchers.IO) {
            categoriesDao.getCategories()
        }
```

2024-04-19 06:16 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/RecipesRepository.kt
> +    suspend fun addCategories(categories: List<Category>?) {
если у тебя при нулевом значении в методе ничего не делается, то нет смысла делать параметр нулябельным:
```Kotlin
    suspend fun addCategories(categories: List<Category>) {
    // ...
```

2024-04-19 06:16 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesViewModel.kt
> +                categoriesList = recipesRepository.getCategoriesFromCash(),
getCategoriesFrom**Cache**

2024-04-19 06:16 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesViewModel.kt
> +                isLoading = false
Можно не ходить в базу лишний раз:
```Kotlin
    _categoriesUiState.value = _categoriesUiState.value?.copy(isLoading = true)

    val cache = recipesRepository.getCategoriesFromCash()
    _categoriesUiState.value = _categoriesUiState.value?.copy(categoriesList = cache)

    val remote = recipesRepository.getCategories()
        ?.apply { recipesRepository.addCategories(this) }

    _categoriesUiState.value = _categoriesUiState.value
        ?.copy(categoriesList = remote, isLoading = false)
```

2024-04-19 10:01 UTC, toto-neutrino1 commented on app/src/main/java/com/example/recipeapp/data/RecipesDatabase.kt
> +            INSTANCE ?: synchronized(this) {
А сейчас Room ещё не внедрена?

2024-04-22 18:33 UTC, merged