RA-06 entities generating for local database
toto-neutrino1/RecipeApp pull request #4
Opened 2023-12-17 21:12 UTC by toto-neutrino1

2023-12-18 13:42 UTC, ievetrov requested changes

2023-12-18 13:42 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
> +                imageUrl = "burger.png"),
если для этого файла применишь автоформатирование – увидишь как проставится скобка закрытия параметров. так стиль будет более корректен

2023-12-18 13:42 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +    val imageUrl: String
хорошо, я бы еще добавлял для последнего свойства trailling comma

2023-12-18 14:56 UTC, toto-neutrino1 commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
> +                imageUrl = "burger.png"),
Пока следил за параметрами, забыл про форматирование )

2023-12-19 12:43 UTC, ievetrov approved these changes

2023-12-19 13:57 UTC, merged