RA-07 implement basic screen layout with categories list
toto-neutrino1/RecipeApp pull request #5
Opened 2023-12-25 13:35 UTC by toto-neutrino1

1) Высоту ConstraintLayout задал как **wrap_content**, т.к. размер изображения ей полностью соответствует.

2) Из-за того, что скругления у карточек сверху и снизу разные, сделал это рабочим (но подозреваю неоптимальным) способом, а именно - сначала задал все скругления одинаковыми аттрибутом **CardCornerRadius** = 8dp (см. стиль **StyleCardView**), а затем добавил аттрибут **layout_marginBottom** = -8dp (значение отрицательное).
Как лучше всего задать скругления карточек, когда для разных углов это надо сделать по-разному?

2023-12-25 21:35 UTC, ievetrov requested changes

2023-12-25 21:35 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Не забывай применять автоформатирование. В том числе и в разметках. Когда все атрибуты стоят на своих местах (в порядковом смысле) - со временем привыкаешь и быстро ориентируешься при их считывании.

2023-12-25 21:35 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
форматирование

2023-12-25 21:35 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/tvCategoryDescription"
попробуй в атрибут текста вписать более длинный текст. отступ в правой части карточки также должен сохраняться. это относится и к заголовку

2023-12-25 21:35 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/tvCategoryDescription"
также для этого элемента нужна стилизация

2023-12-25 23:54 UTC, toto-neutrino1 commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/tvCategoryDescription"
Насчёт более длинного текста - добавил аттрибут **paddingEnd** для обоих TextView.

Правда, пришлось им присвоить разные значения, и полного сходства с макетом в Figma добиться не удалось, например, переносы текста совпадают не полностью, насколько это критично?

Пример:
Текст "Пицца на любой вкус и цвет. Лучшая подборка для тебя" **в Figma выглядит так**:
Пицца на любой вкус 
и цвет. Лучшая 
подборка для тебя

**В моём случае выглядит так**:
Пицца на любой вкус 
и цвет. Лучшая подборка 
для тебя

2023-12-26 00:01 UTC, toto-neutrino1 commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/tvCategoryDescription"
В RA-06 если я правильно понял под burgerCategories имелся в виду listCategories, который я перенёс полностью из фрагмента категории в object STUB

2023-12-26 05:43 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/tvCategoryDescription"
> переносы текста совпадают не полностью, насколько это критично?

это не критично, тк учитывай что на разных устройствах может быть разное разрешение экрана и плотность пикселей. наша задача делать верстку адаптивной.

ответ на второй вопрос тот же. ширина карточек будет динамически меняться, мы задаем только высоту изображений

2023-12-26 05:46 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/tvCategoryDescription"
> В RA-06 если я правильно понял под burgerCategories имелся в виду listCategories, который я перенёс полностью из фрагмента категории в object STUB

да, я допустил ошибку. тут просто должно быть categories)

2023-12-26 11:00 UTC, toto-neutrino1 commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/tvCategoryDescription"
Конкретную высоту задал только у картинки; у TextViews высоту не стал конкретную задавать, т.к. иначе часть текста обрезается (на эмуляторе Pixel 4)

2023-12-26 14:14 UTC, ievetrov approved these changes

2023-12-26 14:19 UTC, merged