RA-08 implement recyclerView with categoriesList
toto-neutrino1/RecipeApp pull request #6
Opened 2023-12-29 20:57 UTC by toto-neutrino1

Слушатель кликов для viewHolder будет реализован в одном из следующих этапов

2023-12-30 15:30 UTC, ievetrov requested changes

2023-12-30 15:30 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListAdapter.kt
> +    (
скобку основного конструктора принято открывать но той же строке, где написана декларация класса

2023-12-30 15:30 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
>          <ImageView
ContentDescription в Android — это описание элементов интерфейса для пользователей с ограничениями зрения, использующих средства чтения с экрана, например, TalkBack. Он важен для интерактивных элементов (кнопок, ссылок), чтобы объяснить их функции. Для декоративных элементов можно установить "@null", чтобы они игнорировались средствами чтения. Отсутствие contentDescription может сделать приложение недоступным для пользователей с нарушениями зрения.

2023-12-30 15:30 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListAdapter.kt
> +            Log.e("onBindViewHolder, categoryImage", e.stackTrace.toString())
- можно что-то более конкретизированное, типа `asset error ${e.printStackTrace()}`
- для распечатки стектрейса есть отдельный метод на примере выше

2023-12-30 18:16 UTC, toto-neutrino1 commented on app/src/main/res/layout/item_category.xml
>          <ImageView
Тут вроде добавил всё что нужно, но вопрос правильно ли я это сделал, конкретно в файле **CategoriesListAdapter.kt** для карточки:
- я добавил **contentDescription** для самой карточки CardView, но не стал никак обозначать отдельно ImageView, подразумевая, что при клике на картинку в TallBack должно быть озвучено contentDescription для карточки целиком - это правильный подход или для CardView вообще contentDescription не надо было делать, а сделать только для ImageView и двух TextView?

2023-12-30 18:20 UTC, toto-neutrino1 commented on app/src/main/res/layout/item_category.xml
>          <ImageView
И к комментарию про отступы "- Обрати внимание на отступы. Между ресайклером и кнопками на макете он отличается. Также давай сделаем так, чтобы список вплотную прилегал к картинке в шапке (при прокрутке)":
- чтобы список прилегал вплотную при прокрутке - убрал **marginVertical** в макете **fragment_list_categories.xml**
- в макете **item_category.xml** убрал **marginVertical**, добавил **marginTop** - так нужный отступ 8dp между карточками получилось сделать

2024-01-04 11:52 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
>          <ImageView
> Тут вроде добавил всё что нужно, но вопрос правильно ли я это сделал, конкретно в файле **CategoriesListAdapter.kt** для карточки:
> 
> * я добавил **contentDescription** для самой карточки CardView, но не стал никак обозначать отдельно ImageView, подразумевая, что при клике на картинку в TallBack должно быть озвучено contentDescription для карточки целиком - это правильный подход или для CardView вообще contentDescription не надо было делать, а сделать только для ImageView и двух TextView?

`contentDescription` используется для предоставления текстового описания для не текстовых элементов, таких как изображения, кнопки с иконками и других графических объектов. Для TextView нет необходимости задавать описание, так как скрин ридер озвучит содержимое экрана и так.

Это происходит так: пользователь водит пальцем по экрану и в зависимости от того, где сейчас активно нажатие – происходит озвучивание. Чтобы перейти в конкретную категорию пользователю нужно совершить двойное нажатие в качестве подтверждения перехода на соответствующую категорию. 

Исходя из этого лучше делать `contentDescription` только для картинок. Причем подход у тебя правильный – через адаптер. Можно задавать картинкам категорий что-то "Изображение категории название_категории"

2024-01-04 13:53 UTC, ievetrov requested changes

2024-01-04 13:53 UTC, ievetrov commented on app/src/main/res/values/strings.xml
> +    <string name="categories_button">Кнопка категории</string>
Исходя из комментария выше следует, что описание контента для кнопок также не требуется.

2024-01-04 13:53 UTC, ievetrov commented on app/src/main/res/values/strings.xml
> +    <string name="category">Категория</string>
Рекомендую задавать название ресурса в соответствии с ее назначением, соблюдая единый стиль других айтемов. Чтобы при глобальном поиске по проекту (через Shift + Ctrl + F) в выдачу не попадали другие результаты, содержащие этот же текст, и не сбивали с толку.

Лучше уточнить, что это текстовый ресурс с помощью префикса, например, text_ или title_.

2024-01-04 13:54 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
>          <ImageView
> И к комментарию про отступы "- Обрати внимание на отступы. Между ресайклером и кнопками на макете он отличается. Также давай сделаем так, чтобы список вплотную прилегал к картинке в шапке (при прокрутке)":
> 
> * в макете **fragment_list_categories.xml** убрал **marginVertical** - чтобы список прилегал вплотную при прокрутке и чтобы между фрагментом и кнопками было нужное расстояние (уже заданное в макете **activity_main.xml**)
> * в макете **item_category.xml** убрал **marginVertical**, добавил **marginTop** - так нужный отступ 8dp между карточками получилось сделать

все верно, сейчас выглядит четко по макету!

2024-01-04 13:54 UTC, ievetrov commented
По contentDescription отписал в треде выше

2024-01-04 19:02 UTC, ievetrov requested changes

2024-01-04 19:02 UTC, ievetrov commented on app/src/main/java/com/example/recipeapp/CategoriesListAdapter.kt
> +                contentDescription = "Изображение категории ${dataset[position].title}"
Остался захардкоженный текст

2024-01-05 10:36 UTC, ievetrov approved these changes

2024-01-05 20:12 UTC, merged