RA-11 implement screen with recipes list
toto-neutrino1/RecipeApp pull request #9
Opened 2024-01-09 19:12 UTC by toto-neutrino1

Сделал всё, кроме 8 пункта - т.к. я не понял, зачем вешать слушателя кликов на конкретный рецепт (разве RecipeFragment это не последний шаг на пути от категорий до конкретного рецепта?). 
Или при клике на рецепт он должен в избранное добавляться, и слушатель нужен для этого?

8 пункт звучит так:
"Реализовать навигацию по клику на пустой RecipeFragment, при этом в метод replace() не передавать других параметров, кроме mainContainer."

2024-01-10 20:05 UTC, ievetrov commented
> разве RecipeFragment это не последний шаг на пути от категорий до конкретного рецепта?

нет. в дизайне идет так: категории - рецепты категории (конкретной) - экран рецепта

> В макете fragment_recipe.xml TextView не совсем такой, как в Figma

в текущем задании не говорится о реализации экрана с рецептом

> Во фрагмент RecipeFragment при его инициализации (в методе openRecipeByRecipeId()) в качестве Bundle передал пока только часть данных

1. мы еще не дошли до фрагмента с рецептом
2. надо идти по заданию, если надо передать конкретный набор данных ради практики - это зачем-то требуется) ну и я проверяю выполнение каждого пункта задания

2024-01-10 20:08 UTC, ievetrov requested changes

2024-01-10 20:08 UTC, ievetrov commented on app/src/main/assets/burger-avocado.png
картинки надо экспортировать из компонентов. там, где они в оригинальном размере и формы (без скругленных углов)

2024-01-10 20:09 UTC, ievetrov commented
> В макетах fragment_list_recipes.xml и fragment_recipe.xml у изображений сделал фиксированную высоту

все верно. фотографии делаем с фиксированной высотой, все остальное адаптивно

2024-01-10 20:30 UTC, toto-neutrino1 commented
> > разве RecipeFragment это не последний шаг на пути от категорий до конкретного рецепта?
> 
> нет. в дизайне идет так: категории - рецепты категории (конкретной) - экран рецепта
> 
> > В макете fragment_recipe.xml TextView не совсем такой, как в Figma
> 
> в текущем задании не говорится о реализации экрана с рецептом
> 
> > Во фрагмент RecipeFragment при его инициализации (в методе openRecipeByRecipeId()) в качестве Bundle передал пока только часть данных
> 
> 1. мы еще не дошли до фрагмента с рецептом
> 2. надо идти по заданию, если надо передать конкретный набор данных ради практики - это зачем-то требуется) ну и я проверяю выполнение каждого пункта задания


1) Под **RecipeFragment** я понял экран с конкретным рецептом (исходя из названия). А рецепты конкретной категории - **RecipeListFragment**.

2) Экран с рецептом уберу

2024-01-10 20:40 UTC, toto-neutrino1 commented
Т.к. это будет в следующей стори реализовано, удалил:

1) В **RecipeListFragment** в методе **openRecipeByRecipeId()** убрал передачу параметров при создании нового фрагмента в методе replace().

2) Из **RecipeFragment** убрал всё, кроме "шапки". В **fragment_recipe.xml** оставил только TextView, всё остальное пока убрал.

2024-01-11 11:58 UTC, ievetrov approved these changes

2024-01-11 14:29 UTC, merged